// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS3z34cVQr80LcjvS1g-EJHMlIgbMxMRs',
    appId: '1:751380543970:web:3bceec51ca040626eae1bb',
    messagingSenderId: '751380543970',
    projectId: 'aqwanetio',
    authDomain: 'aqwanetio.firebaseapp.com',
    storageBucket: 'aqwanetio.firebasestorage.app',
    measurementId: 'G-DTBBESWWRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTjcUgUxqqe-OIsO1WQfAECedkO1e_o6o',
    appId: '1:751380543970:android:ceb07743037b83baeae1bb',
    messagingSenderId: '751380543970',
    projectId: 'aqwanetio',
    storageBucket: 'aqwanetio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2P341Y4ixaczD9AQSVZ6DVj9HPOAgVPc',
    appId: '1:751380543970:ios:971da3223886fe21eae1bb',
    messagingSenderId: '751380543970',
    projectId: 'aqwanetio',
    storageBucket: 'aqwanetio.firebasestorage.app',
    iosBundleId: 'com.example.aqwanetioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2P341Y4ixaczD9AQSVZ6DVj9HPOAgVPc',
    appId: '1:751380543970:ios:971da3223886fe21eae1bb',
    messagingSenderId: '751380543970',
    projectId: 'aqwanetio',
    storageBucket: 'aqwanetio.firebasestorage.app',
    iosBundleId: 'com.example.aqwanetioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS3z34cVQr80LcjvS1g-EJHMlIgbMxMRs',
    appId: '1:751380543970:web:61e4ddb76a171667eae1bb',
    messagingSenderId: '751380543970',
    projectId: 'aqwanetio',
    authDomain: 'aqwanetio.firebaseapp.com',
    storageBucket: 'aqwanetio.firebasestorage.app',
    measurementId: 'G-VMZLC5Q22Q',
  );
}
